### ISSUE TITLE
generic формат

### ISSUE THREAD

**Issue by asosnoviy** [otymko/acc-export#10]
https://docs.sonarqube.org/latest/analysis/generic-issue/ описание формата подвезли.

**Comment by otymko** [comment]
Огонь! Надо делать)

**Comment by otymko** [comment]
@asosnoviy как раз там есть "effortMinutes" - то что мне нужно было для выгрузки этого из АПК

**Comment by otymko** [comment]
Реализовано в версии [1.0.0 ](https://github.com/otymko/acc-export/releases/tag/1.0.0)
