### ISSUE TITLE
Перезапуск проекта с 0

### ISSUE THREAD

**Issue by Stepa86** [otymko/acc-export#18]
Очень часто бывает, что АПК один раз получил данные по конфе и больше их не обновляет, оставляя ошибку актуальной.

Самый яркий пример - неиспользуемая процедура. После ее удаления, ошибка все равно остается.

Сейчас вручную проект я пересоздаю так:
* Выгружаю настройки проекта в файл. В карточке конфы Файл - Выгрузить настройки конфигурации
* Выгружаю все особенности с вкладки Особенности
* Переименовываю конфу
* Создаю новую и загружаю туда файл. Файл - Загрузить настройки конфигурации
* Открываю мастер проверки, саму проверку не запускаю, а выбираю Вручную - Далее - Далее - Далее - Далее - Получить структуру конфигурации, после этого отменяю проверку.
* В карточке загружаю особенности
* Опционально можно запустить на удаление старую конфу, но это долго

После этого конфа готова и старые ошибки уходят.

Вроде как в АПК в пакетном режиме поддерживается создание проекта и загрузка в него особенностей без таких танцев, но это нужно ковырять.

И делать как то опционально, все таки АПК с нуля работает значительно дольше, чем АПК по готовому проекту работают. У меня доходит до x3

**Comment by otymko** [comment]
@Stepa86 закрываем?

**Comment by fenixnow** [comment]
> Вроде как в АПК в пакетном режиме поддерживается создание проекта и загрузка в него особенностей без таких танцев, но это нужно ковырять.

При чем очень интересно, каждый раз АПК создает новую конфу при запуске через пакетный режим. 
Обратите на это внимание
