### ISSUE TITLE
Не загружаются диагностика, если в строке модуля только одна колонка

### ISSUE THREAD

**Issue by VladFrost** [otymko/acc-export#19]
ERROR: Error during SonarQube Scanner execution
ERROR: 2 is not a valid line offset for pointer. File sbm/src/Catalogs/СканированныеДокументыДляПередачиВЭлектронномВиде/Ext/ManagerModule.bsl has 1 character(s) at line 160

Подозрение на эту строку:

https://github.com/otymko/acc-export/blob/develop/src/ВыгрузкаРезультатовПроверки/ObjectModule.bsl#L826

**Comment by otymko** [comment]
@VladFrost Попробую завтра посмотреть
