### ISSUE TITLE
Закрывается АПК

### ISSUE THREAD

**Issue by fenixnow** [otymko/acc-export#21]
1С:Предприятие 8.3 (8.3.14.1694)
Автоматизированная проверка конфигураций, редакция 1.2 (1.2.2.70)

При попытке открыть обработку ВыгрузкаРезультатовПроверки конфигурация просто закрывается.....
В журнале регистрации пусто

**Comment by otymko** [comment]
Нужно запускать приложение с флагом /debug. Обработка заточена под запуск через пакетный режим 1С.

**Comment by fenixnow** [comment]
> Нужно запускать приложение с флагом /debug. Обработка заточена под запуск через пакетный режим 1С.

Все тоже самое bedug помогает, запуск пакетного режима тоже.

**Comment by otymko** [comment]
![image](https://user-images.githubusercontent.com/11651847/56623989-e405f500-6660-11e9-8459-df638486044d.png)
и в режиме предприятия
![image](https://user-images.githubusercontent.com/11651847/56624003-faac4c00-6660-11e9-848d-221ba4182e03.png)

**Comment by fenixnow** [comment]
Ок, проблему решили.
