### ISSUE TITLE
При попытке выгрузки диагностик возникает ошибка

### ISSUE THREAD

**Issue by fenixnow** [otymko/acc-export#22]
Без флага проверить 
![image](https://user-images.githubusercontent.com/13418562/56640359-7d420500-667b-11e9-9e71-0fe6404ed4d6.png)

С флагом
![image](https://user-images.githubusercontent.com/13418562/56640419-a95d8600-667b-11e9-858b-af521d47ccdd.png)

**Comment by otymko** [comment]
Используйте версию из develop ветки. Она адаптирована под последнюю версию.
https://github.com/otymko/acc-export/tree/develop

**Comment by fenixnow** [comment]
супер
