### ISSUE TITLE
Расшение

### ISSUE THREAD

**Issue by fenixnow** [otymko/acc-export#23]
D:\Sonar>oscript updatecr.os
{Модуль D:\Sonar\updatecr.os / Ошибка в строке: 15 / Свойство объекта не обнаружено (Расшение)}

Можно узнать что это значит?

**Comment by otymko** [comment]
Я думаю что опечатка. Можете у себя в файле пока это поправить

**Comment by fenixnow** [comment]
Это же видно из ошибки :) updater.os строка 18

**Comment by fenixnow** [comment]
Я не очень понимаю на что поправить?

**Comment by otymko** [comment]
Файл в develop обновлен. Юзайте)

**Comment by otymko** [comment]
Можно брать из релиза: https://github.com/otymko/acc-export/releases/tag/1.1.0
