### ISSUE TITLE
Ошибка парсинга acc-json 

### ISSUE THREAD

**Issue by otymko** [otymko/acc-export#28]
Перенесено из https://github.com/1c-syntax/bsl-language-server/issues/257

Собрал маленькую конфигурацию выполнил проверку через АПК и пытаюсь загрузить данные в SQ.
Ловлю ошибку.
java.lang.IllegalArgumentException: Start pointer [line=3313, lineOffset=0] should be before end pointer [line=3313, lineOffset=0]

Выглядит так, как будто не удается корректно посчитать смещение.

Самое интересное - удаляю место с ошибкой(большой блок) и снова ошибка в этом же месте

**Comment by otymko** [comment]
@Stepa86 давай просто сделаем, чтобы вешалось на модуль. По позиционированию и потом сам посмотрю, как сделать, чтобы не вылетало.

**Comment by KrapivinAndrey** [comment]
Самое интересное - до строки 3313 точно такие же range - не валяться.
Если удалить часть проверки - ошибка все равно будет в строке 3313

**Comment by Stepa86** [comment]
В моей обработке впринципе не прописываются оффсеты. Может джсон не подменяется, просто?

**Comment by otymko** [comment]
@KrapivinAndrey пришли файл

**Comment by KrapivinAndrey** [comment]
@otymko Лови
[acc-json.zip](https://github.com/otymko/acc-export/files/3371418/acc-json.zip)

**Comment by otymko** [comment]
@KrapivinAndrey попробуй 
[acc-export.zip](https://github.com/otymko/acc-export/files/3371441/acc-export.zip)
