### ISSUE TITLE
При выгрузке ошибки добавить в выгрузку (отчет) ссылку на стандарт ИТС

### ISSUE THREAD

**Issue by pimchest** [otymko/acc-export#44]

**Comment by Stepa86** [comment]
1) В новой версии плагина есть подгрузка правил из АПК.
2) Либо можно поставить плагин https://github.com/fortify-ps/sonarqube-scanner-externalissue-rule . В деве уже есть выгрузка правил под этот плагин - там есть описание и ссылка.

@otymko Можно закрыть, ящитаю
