### ISSUE TITLE
Добавить уточнение для "Орфографическая ошибка в тексте модуля"

### ISSUE THREAD

**Issue by Stepa86** [otymko/acc-export#5]
Не добавляется уточнение к ошибке. Пишется, что есть ошибка в этой строке, но не пишется какая.

**Comment by otymko** [comment]
Можно dev ветке посмотреть

**Comment by Stepa86** [comment]
Я еще у себя не проверял, но есть опасения, что поиск элемента по уиду в моей базе не сработает.

Так же считаю, что нужно разделить абстракции на 1) получение данных из АПК, 2) наполнение таблицы результатов и 3) вывод в файл
И работа с уточнением это скорее 2ая абстракция, а не 1ая.

Сегодня/завтра кину свой вариант PRом

**Comment by otymko** [comment]
@Stepa86 Почему не сработает? Есть макет проверок, по которому изначально ведется заполнение базы.
![image](https://user-images.githubusercontent.com/11651847/52258680-98418a80-2952-11e9-8e7c-bf2474c0d3ce.png)

**Comment by otymko** [comment]
@Stepa86 По поводу уточнения можно сделать и во втором этапе (Подготовка), т.к. скорее всего работ с уточнением станет больше.

**Comment by Stepa86** [comment]
Как доберусь, проверю и узнаю наверняка
