### ISSUE TITLE
Поддержка выгрузки EDT

### ISSUE THREAD

**Issue by Stepa86** [otymko/acc-export#6]
Формировать пути к файлам в формате EDT

**Comment by VladFrost** [comment]
@Stepa86 а ты здесь делал что-нибудь? Я попробовал и у меня вот что получилось:
```
Подготовлено ошибок: 96 729
Для выгрузки: 0 ошибок
Файл с ошибками создан: E:\J\workspace\SQ/sbm\\acc-generic-issue.json

E:\J\workspace\SQ\sbm\acc-generic-issue.json
{
"issues": []
}
```

**Comment by Stepa86** [comment]
> @Stepa86 а ты здесь делал что-нибудь? Я попробовал и у меня вот что получилось:
> 

Еще не делал, но уже в ближайших планах. Там логика при выгрузке, что формируется путь к файлу, он ищется в исходниках, и если не найден, то ошибка пропускается. Вот у тебя все и пропустились
