### ISSUE TITLE
Не проставляется код после acc-

### ISSUE THREAD

**Issue by Stepa86** [otymko/acc-export#7]
![image](https://user-images.githubusercontent.com/25096392/52210799-18a3b500-2899-11e9-8096-3ede52858dd7.png)

**Comment by otymko** [comment]
Теперь так:
![image](https://user-images.githubusercontent.com/11651847/52245884-ff8d1980-2915-11e9-98d1-3f661620b86d.png)

**Comment by otymko** [comment]
Можно dev ветке посмотреть
